/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the GetAccounts4XXResponseErrorsInnerSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccounts4XXResponseErrorsInnerSource{}

// GetAccounts4XXResponseErrorsInnerSource struct for GetAccounts4XXResponseErrorsInnerSource
type GetAccounts4XXResponseErrorsInnerSource struct {
	Pointer *string `json:"pointer,omitempty"`
	Parameter *string `json:"parameter,omitempty"`
}

// NewGetAccounts4XXResponseErrorsInnerSource instantiates a new GetAccounts4XXResponseErrorsInnerSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccounts4XXResponseErrorsInnerSource() *GetAccounts4XXResponseErrorsInnerSource {
	this := GetAccounts4XXResponseErrorsInnerSource{}
	return &this
}

// NewGetAccounts4XXResponseErrorsInnerSourceWithDefaults instantiates a new GetAccounts4XXResponseErrorsInnerSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccounts4XXResponseErrorsInnerSourceWithDefaults() *GetAccounts4XXResponseErrorsInnerSource {
	this := GetAccounts4XXResponseErrorsInnerSource{}
	return &this
}

// GetPointer returns the Pointer field value if set, zero value otherwise.
func (o *GetAccounts4XXResponseErrorsInnerSource) GetPointer() string {
	if o == nil || IsNil(o.Pointer) {
		var ret string
		return ret
	}
	return *o.Pointer
}

// GetPointerOk returns a tuple with the Pointer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccounts4XXResponseErrorsInnerSource) GetPointerOk() (*string, bool) {
	if o == nil || IsNil(o.Pointer) {
		return nil, false
	}
	return o.Pointer, true
}

// HasPointer returns a boolean if a field has been set.
func (o *GetAccounts4XXResponseErrorsInnerSource) HasPointer() bool {
	if o != nil && !IsNil(o.Pointer) {
		return true
	}

	return false
}

// SetPointer gets a reference to the given string and assigns it to the Pointer field.
func (o *GetAccounts4XXResponseErrorsInnerSource) SetPointer(v string) {
	o.Pointer = &v
}

// GetParameter returns the Parameter field value if set, zero value otherwise.
func (o *GetAccounts4XXResponseErrorsInnerSource) GetParameter() string {
	if o == nil || IsNil(o.Parameter) {
		var ret string
		return ret
	}
	return *o.Parameter
}

// GetParameterOk returns a tuple with the Parameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccounts4XXResponseErrorsInnerSource) GetParameterOk() (*string, bool) {
	if o == nil || IsNil(o.Parameter) {
		return nil, false
	}
	return o.Parameter, true
}

// HasParameter returns a boolean if a field has been set.
func (o *GetAccounts4XXResponseErrorsInnerSource) HasParameter() bool {
	if o != nil && !IsNil(o.Parameter) {
		return true
	}

	return false
}

// SetParameter gets a reference to the given string and assigns it to the Parameter field.
func (o *GetAccounts4XXResponseErrorsInnerSource) SetParameter(v string) {
	o.Parameter = &v
}

func (o GetAccounts4XXResponseErrorsInnerSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccounts4XXResponseErrorsInnerSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pointer) {
		toSerialize["pointer"] = o.Pointer
	}
	if !IsNil(o.Parameter) {
		toSerialize["parameter"] = o.Parameter
	}
	return toSerialize, nil
}

type NullableGetAccounts4XXResponseErrorsInnerSource struct {
	value *GetAccounts4XXResponseErrorsInnerSource
	isSet bool
}

func (v NullableGetAccounts4XXResponseErrorsInnerSource) Get() *GetAccounts4XXResponseErrorsInnerSource {
	return v.value
}

func (v *NullableGetAccounts4XXResponseErrorsInnerSource) Set(val *GetAccounts4XXResponseErrorsInnerSource) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccounts4XXResponseErrorsInnerSource) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccounts4XXResponseErrorsInnerSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccounts4XXResponseErrorsInnerSource(val *GetAccounts4XXResponseErrorsInnerSource) *NullableGetAccounts4XXResponseErrorsInnerSource {
	return &NullableGetAccounts4XXResponseErrorsInnerSource{value: val, isSet: true}
}

func (v NullableGetAccounts4XXResponseErrorsInnerSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccounts4XXResponseErrorsInnerSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


