/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TemplateResponseObjectResourceAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponseObjectResourceAttributes{}

// TemplateResponseObjectResourceAttributes struct for TemplateResponseObjectResourceAttributes
type TemplateResponseObjectResourceAttributes struct {
	// The name of the template
	Name string `json:"name"`
	// `editor_type` has a fixed set of values: * SYSTEM_DRAGGABLE: indicates a drag-and-drop editor template * SIMPLE: A rich text editor template * CODE: A custom HTML template * USER_DRAGGABLE: A hybrid template, using custom HTML in the drag-and-drop editor
	EditorType string `json:"editor_type"`
	// The rendered HTML of the template
	Html string `json:"html"`
	// The template plain_text
	Text NullableString `json:"text,omitempty"`
	// The date the template was created in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
	Created NullableTime `json:"created,omitempty"`
	// The date the template was updated in ISO 8601 format (YYYY-MM-DDTHH:MM:SS.mmmmmm)
	Updated NullableTime `json:"updated,omitempty"`
}

type _TemplateResponseObjectResourceAttributes TemplateResponseObjectResourceAttributes

// NewTemplateResponseObjectResourceAttributes instantiates a new TemplateResponseObjectResourceAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseObjectResourceAttributes(name string, editorType string, html string) *TemplateResponseObjectResourceAttributes {
	this := TemplateResponseObjectResourceAttributes{}
	this.Name = name
	this.EditorType = editorType
	this.Html = html
	return &this
}

// NewTemplateResponseObjectResourceAttributesWithDefaults instantiates a new TemplateResponseObjectResourceAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseObjectResourceAttributesWithDefaults() *TemplateResponseObjectResourceAttributes {
	this := TemplateResponseObjectResourceAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *TemplateResponseObjectResourceAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseObjectResourceAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TemplateResponseObjectResourceAttributes) SetName(v string) {
	o.Name = v
}

// GetEditorType returns the EditorType field value
func (o *TemplateResponseObjectResourceAttributes) GetEditorType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EditorType
}

// GetEditorTypeOk returns a tuple with the EditorType field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseObjectResourceAttributes) GetEditorTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EditorType, true
}

// SetEditorType sets field value
func (o *TemplateResponseObjectResourceAttributes) SetEditorType(v string) {
	o.EditorType = v
}

// GetHtml returns the Html field value
func (o *TemplateResponseObjectResourceAttributes) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseObjectResourceAttributes) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *TemplateResponseObjectResourceAttributes) SetHtml(v string) {
	o.Html = v
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateResponseObjectResourceAttributes) GetText() string {
	if o == nil || IsNil(o.Text.Get()) {
		var ret string
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponseObjectResourceAttributes) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *TemplateResponseObjectResourceAttributes) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableString and assigns it to the Text field.
func (o *TemplateResponseObjectResourceAttributes) SetText(v string) {
	o.Text.Set(&v)
}
// SetTextNil sets the value for Text to be an explicit nil
func (o *TemplateResponseObjectResourceAttributes) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *TemplateResponseObjectResourceAttributes) UnsetText() {
	o.Text.Unset()
}

// GetCreated returns the Created field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateResponseObjectResourceAttributes) GetCreated() time.Time {
	if o == nil || IsNil(o.Created.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponseObjectResourceAttributes) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// HasCreated returns a boolean if a field has been set.
func (o *TemplateResponseObjectResourceAttributes) HasCreated() bool {
	if o != nil && o.Created.IsSet() {
		return true
	}

	return false
}

// SetCreated gets a reference to the given NullableTime and assigns it to the Created field.
func (o *TemplateResponseObjectResourceAttributes) SetCreated(v time.Time) {
	o.Created.Set(&v)
}
// SetCreatedNil sets the value for Created to be an explicit nil
func (o *TemplateResponseObjectResourceAttributes) SetCreatedNil() {
	o.Created.Set(nil)
}

// UnsetCreated ensures that no value is present for Created, not even an explicit nil
func (o *TemplateResponseObjectResourceAttributes) UnsetCreated() {
	o.Created.Unset()
}

// GetUpdated returns the Updated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TemplateResponseObjectResourceAttributes) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Updated.Get()
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TemplateResponseObjectResourceAttributes) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Updated.Get(), o.Updated.IsSet()
}

// HasUpdated returns a boolean if a field has been set.
func (o *TemplateResponseObjectResourceAttributes) HasUpdated() bool {
	if o != nil && o.Updated.IsSet() {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given NullableTime and assigns it to the Updated field.
func (o *TemplateResponseObjectResourceAttributes) SetUpdated(v time.Time) {
	o.Updated.Set(&v)
}
// SetUpdatedNil sets the value for Updated to be an explicit nil
func (o *TemplateResponseObjectResourceAttributes) SetUpdatedNil() {
	o.Updated.Set(nil)
}

// UnsetUpdated ensures that no value is present for Updated, not even an explicit nil
func (o *TemplateResponseObjectResourceAttributes) UnsetUpdated() {
	o.Updated.Unset()
}

func (o TemplateResponseObjectResourceAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponseObjectResourceAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["editor_type"] = o.EditorType
	toSerialize["html"] = o.Html
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.Created.IsSet() {
		toSerialize["created"] = o.Created.Get()
	}
	if o.Updated.IsSet() {
		toSerialize["updated"] = o.Updated.Get()
	}
	return toSerialize, nil
}

func (o *TemplateResponseObjectResourceAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"editor_type",
		"html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateResponseObjectResourceAttributes := _TemplateResponseObjectResourceAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateResponseObjectResourceAttributes)

	if err != nil {
		return err
	}

	*o = TemplateResponseObjectResourceAttributes(varTemplateResponseObjectResourceAttributes)

	return err
}

type NullableTemplateResponseObjectResourceAttributes struct {
	value *TemplateResponseObjectResourceAttributes
	isSet bool
}

func (v NullableTemplateResponseObjectResourceAttributes) Get() *TemplateResponseObjectResourceAttributes {
	return v.value
}

func (v *NullableTemplateResponseObjectResourceAttributes) Set(val *TemplateResponseObjectResourceAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseObjectResourceAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseObjectResourceAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseObjectResourceAttributes(val *TemplateResponseObjectResourceAttributes) *NullableTemplateResponseObjectResourceAttributes {
	return &NullableTemplateResponseObjectResourceAttributes{value: val, isSet: true}
}

func (v NullableTemplateResponseObjectResourceAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseObjectResourceAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


