/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfilePartialUpdateQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfilePartialUpdateQueryResourceObject{}

// ProfilePartialUpdateQueryResourceObject struct for ProfilePartialUpdateQueryResourceObject
type ProfilePartialUpdateQueryResourceObject struct {
	Type ProfileEnum `json:"type"`
	// Primary key that uniquely identifies this profile. Generated by Klaviyo.
	Id string `json:"id"`
	Attributes ProfilePartialUpdateQueryResourceObjectAttributes `json:"attributes"`
	Meta *ProfileMeta `json:"meta,omitempty"`
}

type _ProfilePartialUpdateQueryResourceObject ProfilePartialUpdateQueryResourceObject

// NewProfilePartialUpdateQueryResourceObject instantiates a new ProfilePartialUpdateQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfilePartialUpdateQueryResourceObject(type_ ProfileEnum, id string, attributes ProfilePartialUpdateQueryResourceObjectAttributes) *ProfilePartialUpdateQueryResourceObject {
	this := ProfilePartialUpdateQueryResourceObject{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	return &this
}

// NewProfilePartialUpdateQueryResourceObjectWithDefaults instantiates a new ProfilePartialUpdateQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfilePartialUpdateQueryResourceObjectWithDefaults() *ProfilePartialUpdateQueryResourceObject {
	this := ProfilePartialUpdateQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *ProfilePartialUpdateQueryResourceObject) GetType() ProfileEnum {
	if o == nil {
		var ret ProfileEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProfilePartialUpdateQueryResourceObject) GetTypeOk() (*ProfileEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProfilePartialUpdateQueryResourceObject) SetType(v ProfileEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ProfilePartialUpdateQueryResourceObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProfilePartialUpdateQueryResourceObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProfilePartialUpdateQueryResourceObject) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *ProfilePartialUpdateQueryResourceObject) GetAttributes() ProfilePartialUpdateQueryResourceObjectAttributes {
	if o == nil {
		var ret ProfilePartialUpdateQueryResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ProfilePartialUpdateQueryResourceObject) GetAttributesOk() (*ProfilePartialUpdateQueryResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ProfilePartialUpdateQueryResourceObject) SetAttributes(v ProfilePartialUpdateQueryResourceObjectAttributes) {
	o.Attributes = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ProfilePartialUpdateQueryResourceObject) GetMeta() ProfileMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ProfileMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfilePartialUpdateQueryResourceObject) GetMetaOk() (*ProfileMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ProfilePartialUpdateQueryResourceObject) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ProfileMeta and assigns it to the Meta field.
func (o *ProfilePartialUpdateQueryResourceObject) SetMeta(v ProfileMeta) {
	o.Meta = &v
}

func (o ProfilePartialUpdateQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfilePartialUpdateQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *ProfilePartialUpdateQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfilePartialUpdateQueryResourceObject := _ProfilePartialUpdateQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfilePartialUpdateQueryResourceObject)

	if err != nil {
		return err
	}

	*o = ProfilePartialUpdateQueryResourceObject(varProfilePartialUpdateQueryResourceObject)

	return err
}

type NullableProfilePartialUpdateQueryResourceObject struct {
	value *ProfilePartialUpdateQueryResourceObject
	isSet bool
}

func (v NullableProfilePartialUpdateQueryResourceObject) Get() *ProfilePartialUpdateQueryResourceObject {
	return v.value
}

func (v *NullableProfilePartialUpdateQueryResourceObject) Set(val *ProfilePartialUpdateQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableProfilePartialUpdateQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableProfilePartialUpdateQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfilePartialUpdateQueryResourceObject(val *ProfilePartialUpdateQueryResourceObject) *NullableProfilePartialUpdateQueryResourceObject {
	return &NullableProfilePartialUpdateQueryResourceObject{value: val, isSet: true}
}

func (v NullableProfilePartialUpdateQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfilePartialUpdateQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


