/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PushTokenUnregisterQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PushTokenUnregisterQuery{}

// PushTokenUnregisterQuery struct for PushTokenUnregisterQuery
type PushTokenUnregisterQuery struct {
	Data PushTokenUnregisterQueryResourceObject `json:"data"`
}

type _PushTokenUnregisterQuery PushTokenUnregisterQuery

// NewPushTokenUnregisterQuery instantiates a new PushTokenUnregisterQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPushTokenUnregisterQuery(data PushTokenUnregisterQueryResourceObject) *PushTokenUnregisterQuery {
	this := PushTokenUnregisterQuery{}
	this.Data = data
	return &this
}

// NewPushTokenUnregisterQueryWithDefaults instantiates a new PushTokenUnregisterQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPushTokenUnregisterQueryWithDefaults() *PushTokenUnregisterQuery {
	this := PushTokenUnregisterQuery{}
	return &this
}

// GetData returns the Data field value
func (o *PushTokenUnregisterQuery) GetData() PushTokenUnregisterQueryResourceObject {
	if o == nil {
		var ret PushTokenUnregisterQueryResourceObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PushTokenUnregisterQuery) GetDataOk() (*PushTokenUnregisterQueryResourceObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PushTokenUnregisterQuery) SetData(v PushTokenUnregisterQueryResourceObject) {
	o.Data = v
}

func (o PushTokenUnregisterQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PushTokenUnregisterQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PushTokenUnregisterQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPushTokenUnregisterQuery := _PushTokenUnregisterQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPushTokenUnregisterQuery)

	if err != nil {
		return err
	}

	*o = PushTokenUnregisterQuery(varPushTokenUnregisterQuery)

	return err
}

type NullablePushTokenUnregisterQuery struct {
	value *PushTokenUnregisterQuery
	isSet bool
}

func (v NullablePushTokenUnregisterQuery) Get() *PushTokenUnregisterQuery {
	return v.value
}

func (v *NullablePushTokenUnregisterQuery) Set(val *PushTokenUnregisterQuery) {
	v.value = val
	v.isSet = true
}

func (v NullablePushTokenUnregisterQuery) IsSet() bool {
	return v.isSet
}

func (v *NullablePushTokenUnregisterQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePushTokenUnregisterQuery(val *PushTokenUnregisterQuery) *NullablePushTokenUnregisterQuery {
	return &NullablePushTokenUnregisterQuery{value: val, isSet: true}
}

func (v NullablePushTokenUnregisterQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePushTokenUnregisterQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


