/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships{}

// GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships struct for GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships
type GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships struct {
	Categories *GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile `json:"categories,omitempty"`
}

// NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships instantiates a new GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships() *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships {
	this := GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships{}
	return &this
}

// NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationshipsWithDefaults instantiates a new GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationshipsWithDefaults() *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships {
	this := GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) GetCategories() GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile {
	if o == nil || IsNil(o.Categories) {
		var ret GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile
		return ret
	}
	return *o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) GetCategoriesOk() (*GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile and assigns it to the Categories field.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) SetCategories(v GetCouponCodeResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsProfile) {
	o.Categories = &v
}

func (o GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

type NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships struct {
	value *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships
	isSet bool
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) Get() *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships {
	return v.value
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) Set(val *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships(val *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships {
	return &NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships{value: val, isSet: true}
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


