/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventCreateQueryV2ResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventCreateQueryV2ResourceObject{}

// EventCreateQueryV2ResourceObject struct for EventCreateQueryV2ResourceObject
type EventCreateQueryV2ResourceObject struct {
	Type EventEnum `json:"type"`
	Attributes EventCreateQueryV2ResourceObjectAttributes `json:"attributes"`
}

type _EventCreateQueryV2ResourceObject EventCreateQueryV2ResourceObject

// NewEventCreateQueryV2ResourceObject instantiates a new EventCreateQueryV2ResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventCreateQueryV2ResourceObject(type_ EventEnum, attributes EventCreateQueryV2ResourceObjectAttributes) *EventCreateQueryV2ResourceObject {
	this := EventCreateQueryV2ResourceObject{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEventCreateQueryV2ResourceObjectWithDefaults instantiates a new EventCreateQueryV2ResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventCreateQueryV2ResourceObjectWithDefaults() *EventCreateQueryV2ResourceObject {
	this := EventCreateQueryV2ResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *EventCreateQueryV2ResourceObject) GetType() EventEnum {
	if o == nil {
		var ret EventEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EventCreateQueryV2ResourceObject) GetTypeOk() (*EventEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EventCreateQueryV2ResourceObject) SetType(v EventEnum) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EventCreateQueryV2ResourceObject) GetAttributes() EventCreateQueryV2ResourceObjectAttributes {
	if o == nil {
		var ret EventCreateQueryV2ResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EventCreateQueryV2ResourceObject) GetAttributesOk() (*EventCreateQueryV2ResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EventCreateQueryV2ResourceObject) SetAttributes(v EventCreateQueryV2ResourceObjectAttributes) {
	o.Attributes = v
}

func (o EventCreateQueryV2ResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventCreateQueryV2ResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EventCreateQueryV2ResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEventCreateQueryV2ResourceObject := _EventCreateQueryV2ResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEventCreateQueryV2ResourceObject)

	if err != nil {
		return err
	}

	*o = EventCreateQueryV2ResourceObject(varEventCreateQueryV2ResourceObject)

	return err
}

type NullableEventCreateQueryV2ResourceObject struct {
	value *EventCreateQueryV2ResourceObject
	isSet bool
}

func (v NullableEventCreateQueryV2ResourceObject) Get() *EventCreateQueryV2ResourceObject {
	return v.value
}

func (v *NullableEventCreateQueryV2ResourceObject) Set(val *EventCreateQueryV2ResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableEventCreateQueryV2ResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableEventCreateQueryV2ResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventCreateQueryV2ResourceObject(val *EventCreateQueryV2ResourceObject) *NullableEventCreateQueryV2ResourceObject {
	return &NullableEventCreateQueryV2ResourceObject{value: val, isSet: true}
}

func (v NullableEventCreateQueryV2ResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventCreateQueryV2ResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


