/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileImportJobCreateQueryResourceObjectRelationshipsLists type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileImportJobCreateQueryResourceObjectRelationshipsLists{}

// ProfileImportJobCreateQueryResourceObjectRelationshipsLists struct for ProfileImportJobCreateQueryResourceObjectRelationshipsLists
type ProfileImportJobCreateQueryResourceObjectRelationshipsLists struct {
	Data []ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner `json:"data"`
}

type _ProfileImportJobCreateQueryResourceObjectRelationshipsLists ProfileImportJobCreateQueryResourceObjectRelationshipsLists

// NewProfileImportJobCreateQueryResourceObjectRelationshipsLists instantiates a new ProfileImportJobCreateQueryResourceObjectRelationshipsLists object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileImportJobCreateQueryResourceObjectRelationshipsLists(data []ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner) *ProfileImportJobCreateQueryResourceObjectRelationshipsLists {
	this := ProfileImportJobCreateQueryResourceObjectRelationshipsLists{}
	this.Data = data
	return &this
}

// NewProfileImportJobCreateQueryResourceObjectRelationshipsListsWithDefaults instantiates a new ProfileImportJobCreateQueryResourceObjectRelationshipsLists object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileImportJobCreateQueryResourceObjectRelationshipsListsWithDefaults() *ProfileImportJobCreateQueryResourceObjectRelationshipsLists {
	this := ProfileImportJobCreateQueryResourceObjectRelationshipsLists{}
	return &this
}

// GetData returns the Data field value
func (o *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) GetData() []ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner {
	if o == nil {
		var ret []ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) GetDataOk() ([]ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) SetData(v []ProfileImportJobCreateQueryResourceObjectRelationshipsListsDataInner) {
	o.Data = v
}

func (o ProfileImportJobCreateQueryResourceObjectRelationshipsLists) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileImportJobCreateQueryResourceObjectRelationshipsLists) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileImportJobCreateQueryResourceObjectRelationshipsLists := _ProfileImportJobCreateQueryResourceObjectRelationshipsLists{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfileImportJobCreateQueryResourceObjectRelationshipsLists)

	if err != nil {
		return err
	}

	*o = ProfileImportJobCreateQueryResourceObjectRelationshipsLists(varProfileImportJobCreateQueryResourceObjectRelationshipsLists)

	return err
}

type NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists struct {
	value *ProfileImportJobCreateQueryResourceObjectRelationshipsLists
	isSet bool
}

func (v NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) Get() *ProfileImportJobCreateQueryResourceObjectRelationshipsLists {
	return v.value
}

func (v *NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) Set(val *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileImportJobCreateQueryResourceObjectRelationshipsLists(val *ProfileImportJobCreateQueryResourceObjectRelationshipsLists) *NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists {
	return &NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists{value: val, isSet: true}
}

func (v NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileImportJobCreateQueryResourceObjectRelationshipsLists) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


