/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostImageResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostImageResponseData{}

// PostImageResponseData struct for PostImageResponseData
type PostImageResponseData struct {
	Type ImageEnum `json:"type"`
	// The ID of the image
	Id string `json:"id"`
	Attributes ImageResponseObjectResourceAttributes `json:"attributes"`
	Links ObjectLinks `json:"links"`
}

type _PostImageResponseData PostImageResponseData

// NewPostImageResponseData instantiates a new PostImageResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostImageResponseData(type_ ImageEnum, id string, attributes ImageResponseObjectResourceAttributes, links ObjectLinks) *PostImageResponseData {
	this := PostImageResponseData{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewPostImageResponseDataWithDefaults instantiates a new PostImageResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostImageResponseDataWithDefaults() *PostImageResponseData {
	this := PostImageResponseData{}
	return &this
}

// GetType returns the Type field value
func (o *PostImageResponseData) GetType() ImageEnum {
	if o == nil {
		var ret ImageEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PostImageResponseData) GetTypeOk() (*ImageEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PostImageResponseData) SetType(v ImageEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *PostImageResponseData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PostImageResponseData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PostImageResponseData) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *PostImageResponseData) GetAttributes() ImageResponseObjectResourceAttributes {
	if o == nil {
		var ret ImageResponseObjectResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PostImageResponseData) GetAttributesOk() (*ImageResponseObjectResourceAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PostImageResponseData) SetAttributes(v ImageResponseObjectResourceAttributes) {
	o.Attributes = v
}

// GetLinks returns the Links field value
func (o *PostImageResponseData) GetLinks() ObjectLinks {
	if o == nil {
		var ret ObjectLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PostImageResponseData) GetLinksOk() (*ObjectLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *PostImageResponseData) SetLinks(v ObjectLinks) {
	o.Links = v
}

func (o PostImageResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostImageResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *PostImageResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostImageResponseData := _PostImageResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostImageResponseData)

	if err != nil {
		return err
	}

	*o = PostImageResponseData(varPostImageResponseData)

	return err
}

type NullablePostImageResponseData struct {
	value *PostImageResponseData
	isSet bool
}

func (v NullablePostImageResponseData) Get() *PostImageResponseData {
	return v.value
}

func (v *NullablePostImageResponseData) Set(val *PostImageResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImageResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImageResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImageResponseData(val *PostImageResponseData) *NullablePostImageResponseData {
	return &NullablePostImageResponseData{value: val, isSet: true}
}

func (v NullablePostImageResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImageResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


