/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"fmt"
)

// FlowEnum the model 'FlowEnum'
type FlowEnum string

// List of FlowEnum
const (
	FLOW FlowEnum = "flow"
)

// All allowed values of FlowEnum enum
var AllowedFlowEnumEnumValues = []FlowEnum{
	"flow",
}

func (v *FlowEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FlowEnum(value)
	for _, existing := range AllowedFlowEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FlowEnum", value)
}

// NewFlowEnumFromValue returns a pointer to a valid FlowEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFlowEnumFromValue(v string) (*FlowEnum, error) {
	ev := FlowEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FlowEnum: valid values are %v", v, AllowedFlowEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FlowEnum) IsValid() bool {
	for _, existing := range AllowedFlowEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to FlowEnum value
func (v FlowEnum) Ptr() *FlowEnum {
	return &v
}

type NullableFlowEnum struct {
	value *FlowEnum
	isSet bool
}

func (v NullableFlowEnum) Get() *FlowEnum {
	return v.value
}

func (v *NullableFlowEnum) Set(val *FlowEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableFlowEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableFlowEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlowEnum(val *FlowEnum) *NullableFlowEnum {
	return &NullableFlowEnum{value: val, isSet: true}
}

func (v NullableFlowEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlowEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

