/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListPartialUpdateQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPartialUpdateQueryResourceObject{}

// ListPartialUpdateQueryResourceObject struct for ListPartialUpdateQueryResourceObject
type ListPartialUpdateQueryResourceObject struct {
	Type ListEnum `json:"type"`
	// Primary key that uniquely identifies this list. Generated by Klaviyo.
	Id string `json:"id"`
	Attributes ListCreateQueryResourceObjectAttributes `json:"attributes"`
}

type _ListPartialUpdateQueryResourceObject ListPartialUpdateQueryResourceObject

// NewListPartialUpdateQueryResourceObject instantiates a new ListPartialUpdateQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPartialUpdateQueryResourceObject(type_ ListEnum, id string, attributes ListCreateQueryResourceObjectAttributes) *ListPartialUpdateQueryResourceObject {
	this := ListPartialUpdateQueryResourceObject{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	return &this
}

// NewListPartialUpdateQueryResourceObjectWithDefaults instantiates a new ListPartialUpdateQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPartialUpdateQueryResourceObjectWithDefaults() *ListPartialUpdateQueryResourceObject {
	this := ListPartialUpdateQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *ListPartialUpdateQueryResourceObject) GetType() ListEnum {
	if o == nil {
		var ret ListEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ListPartialUpdateQueryResourceObject) GetTypeOk() (*ListEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ListPartialUpdateQueryResourceObject) SetType(v ListEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ListPartialUpdateQueryResourceObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListPartialUpdateQueryResourceObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListPartialUpdateQueryResourceObject) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *ListPartialUpdateQueryResourceObject) GetAttributes() ListCreateQueryResourceObjectAttributes {
	if o == nil {
		var ret ListCreateQueryResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ListPartialUpdateQueryResourceObject) GetAttributesOk() (*ListCreateQueryResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ListPartialUpdateQueryResourceObject) SetAttributes(v ListCreateQueryResourceObjectAttributes) {
	o.Attributes = v
}

func (o ListPartialUpdateQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPartialUpdateQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ListPartialUpdateQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPartialUpdateQueryResourceObject := _ListPartialUpdateQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPartialUpdateQueryResourceObject)

	if err != nil {
		return err
	}

	*o = ListPartialUpdateQueryResourceObject(varListPartialUpdateQueryResourceObject)

	return err
}

type NullableListPartialUpdateQueryResourceObject struct {
	value *ListPartialUpdateQueryResourceObject
	isSet bool
}

func (v NullableListPartialUpdateQueryResourceObject) Get() *ListPartialUpdateQueryResourceObject {
	return v.value
}

func (v *NullableListPartialUpdateQueryResourceObject) Set(val *ListPartialUpdateQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableListPartialUpdateQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableListPartialUpdateQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPartialUpdateQueryResourceObject(val *ListPartialUpdateQueryResourceObject) *NullableListPartialUpdateQueryResourceObject {
	return &NullableListPartialUpdateQueryResourceObject{value: val, isSet: true}
}

func (v NullableListPartialUpdateQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPartialUpdateQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


