/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PatchCouponCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchCouponCodeResponse{}

// PatchCouponCodeResponse struct for PatchCouponCodeResponse
type PatchCouponCodeResponse struct {
	Data PostCouponCodeResponseData `json:"data"`
}

type _PatchCouponCodeResponse PatchCouponCodeResponse

// NewPatchCouponCodeResponse instantiates a new PatchCouponCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchCouponCodeResponse(data PostCouponCodeResponseData) *PatchCouponCodeResponse {
	this := PatchCouponCodeResponse{}
	this.Data = data
	return &this
}

// NewPatchCouponCodeResponseWithDefaults instantiates a new PatchCouponCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchCouponCodeResponseWithDefaults() *PatchCouponCodeResponse {
	this := PatchCouponCodeResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PatchCouponCodeResponse) GetData() PostCouponCodeResponseData {
	if o == nil {
		var ret PostCouponCodeResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PatchCouponCodeResponse) GetDataOk() (*PostCouponCodeResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PatchCouponCodeResponse) SetData(v PostCouponCodeResponseData) {
	o.Data = v
}

func (o PatchCouponCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchCouponCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PatchCouponCodeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchCouponCodeResponse := _PatchCouponCodeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchCouponCodeResponse)

	if err != nil {
		return err
	}

	*o = PatchCouponCodeResponse(varPatchCouponCodeResponse)

	return err
}

type NullablePatchCouponCodeResponse struct {
	value *PatchCouponCodeResponse
	isSet bool
}

func (v NullablePatchCouponCodeResponse) Get() *PatchCouponCodeResponse {
	return v.value
}

func (v *NullablePatchCouponCodeResponse) Set(val *PatchCouponCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchCouponCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchCouponCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchCouponCodeResponse(val *PatchCouponCodeResponse) *NullablePatchCouponCodeResponse {
	return &NullablePatchCouponCodeResponse{value: val, isSet: true}
}

func (v NullablePatchCouponCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchCouponCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


