/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems{}

// CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems Array of catalog items to delete.
type CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems struct {
	Data []CatalogItemDeleteQueryResourceObject `json:"data"`
}

type _CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems

// NewCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems instantiates a new CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems(data []CatalogItemDeleteQueryResourceObject) *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems {
	this := CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems{}
	this.Data = data
	return &this
}

// NewCatalogItemDeleteJobCreateQueryResourceObjectAttributesItemsWithDefaults instantiates a new CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogItemDeleteJobCreateQueryResourceObjectAttributesItemsWithDefaults() *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems {
	this := CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems{}
	return &this
}

// GetData returns the Data field value
func (o *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) GetData() []CatalogItemDeleteQueryResourceObject {
	if o == nil {
		var ret []CatalogItemDeleteQueryResourceObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) GetDataOk() ([]CatalogItemDeleteQueryResourceObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) SetData(v []CatalogItemDeleteQueryResourceObject) {
	o.Data = v
}

func (o CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems := _CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems)

	if err != nil {
		return err
	}

	*o = CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems(varCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems)

	return err
}

type NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems struct {
	value *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems
	isSet bool
}

func (v NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) Get() *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems {
	return v.value
}

func (v *NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) Set(val *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems(val *CatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) *NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems {
	return &NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems{value: val, isSet: true}
}

func (v NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogItemDeleteJobCreateQueryResourceObjectAttributesItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


