/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}

// GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct for GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships
type GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct {
	Items *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems `json:"items,omitempty"`
}

// NewGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships instantiates a new GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships() *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	this := GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}
	return &this
}

// NewGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsWithDefaults instantiates a new GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsWithDefaults() *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	this := GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) GetItems() GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems {
	if o == nil || IsNil(o.Items) {
		var ret GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) GetItemsOk() (*GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems and assigns it to the Items field.
func (o *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) SetItems(v GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems) {
	o.Items = &v
}

func (o GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct {
	value *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships
	isSet bool
}

func (v NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Get() *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	return v.value
}

func (v *NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Set(val *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships(val *GetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) *NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	return &NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{value: val, isSet: true}
}

func (v NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogItemCreateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


