/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostProfileImportJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostProfileImportJobResponse{}

// PostProfileImportJobResponse struct for PostProfileImportJobResponse
type PostProfileImportJobResponse struct {
	Data PostProfileImportJobResponseData `json:"data"`
}

type _PostProfileImportJobResponse PostProfileImportJobResponse

// NewPostProfileImportJobResponse instantiates a new PostProfileImportJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostProfileImportJobResponse(data PostProfileImportJobResponseData) *PostProfileImportJobResponse {
	this := PostProfileImportJobResponse{}
	this.Data = data
	return &this
}

// NewPostProfileImportJobResponseWithDefaults instantiates a new PostProfileImportJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostProfileImportJobResponseWithDefaults() *PostProfileImportJobResponse {
	this := PostProfileImportJobResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PostProfileImportJobResponse) GetData() PostProfileImportJobResponseData {
	if o == nil {
		var ret PostProfileImportJobResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PostProfileImportJobResponse) GetDataOk() (*PostProfileImportJobResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PostProfileImportJobResponse) SetData(v PostProfileImportJobResponseData) {
	o.Data = v
}

func (o PostProfileImportJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostProfileImportJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PostProfileImportJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostProfileImportJobResponse := _PostProfileImportJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostProfileImportJobResponse)

	if err != nil {
		return err
	}

	*o = PostProfileImportJobResponse(varPostProfileImportJobResponse)

	return err
}

type NullablePostProfileImportJobResponse struct {
	value *PostProfileImportJobResponse
	isSet bool
}

func (v NullablePostProfileImportJobResponse) Get() *PostProfileImportJobResponse {
	return v.value
}

func (v *NullablePostProfileImportJobResponse) Set(val *PostProfileImportJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostProfileImportJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostProfileImportJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostProfileImportJobResponse(val *PostProfileImportJobResponse) *NullablePostProfileImportJobResponse {
	return &NullablePostProfileImportJobResponse{value: val, isSet: true}
}

func (v NullablePostProfileImportJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostProfileImportJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


