/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}

// GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct for GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships
type GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct {
	Items *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems `json:"items,omitempty"`
}

// NewGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships instantiates a new GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships() *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	this := GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}
	return &this
}

// NewGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsWithDefaults instantiates a new GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsWithDefaults() *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	this := GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) GetItems() GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems {
	if o == nil || IsNil(o.Items) {
		var ret GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) GetItemsOk() (*GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems and assigns it to the Items field.
func (o *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) SetItems(v GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsItems) {
	o.Items = &v
}

func (o GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships struct {
	value *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships
	isSet bool
}

func (v NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Get() *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	return v.value
}

func (v *NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Set(val *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships(val *GetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) *NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	return &NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships{value: val, isSet: true}
}

func (v NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogItemUpdateJobResponseCollectionCompoundDocumentDataInnerAllOfRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


