/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfileImportJobCreateQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileImportJobCreateQueryResourceObject{}

// ProfileImportJobCreateQueryResourceObject struct for ProfileImportJobCreateQueryResourceObject
type ProfileImportJobCreateQueryResourceObject struct {
	Type ProfileBulkImportJobEnum `json:"type"`
	Attributes ProfileImportJobCreateQueryResourceObjectAttributes `json:"attributes"`
	Relationships *ProfileImportJobCreateQueryResourceObjectRelationships `json:"relationships,omitempty"`
}

type _ProfileImportJobCreateQueryResourceObject ProfileImportJobCreateQueryResourceObject

// NewProfileImportJobCreateQueryResourceObject instantiates a new ProfileImportJobCreateQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileImportJobCreateQueryResourceObject(type_ ProfileBulkImportJobEnum, attributes ProfileImportJobCreateQueryResourceObjectAttributes) *ProfileImportJobCreateQueryResourceObject {
	this := ProfileImportJobCreateQueryResourceObject{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewProfileImportJobCreateQueryResourceObjectWithDefaults instantiates a new ProfileImportJobCreateQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileImportJobCreateQueryResourceObjectWithDefaults() *ProfileImportJobCreateQueryResourceObject {
	this := ProfileImportJobCreateQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *ProfileImportJobCreateQueryResourceObject) GetType() ProfileBulkImportJobEnum {
	if o == nil {
		var ret ProfileBulkImportJobEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProfileImportJobCreateQueryResourceObject) GetTypeOk() (*ProfileBulkImportJobEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProfileImportJobCreateQueryResourceObject) SetType(v ProfileBulkImportJobEnum) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ProfileImportJobCreateQueryResourceObject) GetAttributes() ProfileImportJobCreateQueryResourceObjectAttributes {
	if o == nil {
		var ret ProfileImportJobCreateQueryResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ProfileImportJobCreateQueryResourceObject) GetAttributesOk() (*ProfileImportJobCreateQueryResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ProfileImportJobCreateQueryResourceObject) SetAttributes(v ProfileImportJobCreateQueryResourceObjectAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *ProfileImportJobCreateQueryResourceObject) GetRelationships() ProfileImportJobCreateQueryResourceObjectRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret ProfileImportJobCreateQueryResourceObjectRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileImportJobCreateQueryResourceObject) GetRelationshipsOk() (*ProfileImportJobCreateQueryResourceObjectRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *ProfileImportJobCreateQueryResourceObject) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given ProfileImportJobCreateQueryResourceObjectRelationships and assigns it to the Relationships field.
func (o *ProfileImportJobCreateQueryResourceObject) SetRelationships(v ProfileImportJobCreateQueryResourceObjectRelationships) {
	o.Relationships = &v
}

func (o ProfileImportJobCreateQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileImportJobCreateQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *ProfileImportJobCreateQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfileImportJobCreateQueryResourceObject := _ProfileImportJobCreateQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfileImportJobCreateQueryResourceObject)

	if err != nil {
		return err
	}

	*o = ProfileImportJobCreateQueryResourceObject(varProfileImportJobCreateQueryResourceObject)

	return err
}

type NullableProfileImportJobCreateQueryResourceObject struct {
	value *ProfileImportJobCreateQueryResourceObject
	isSet bool
}

func (v NullableProfileImportJobCreateQueryResourceObject) Get() *ProfileImportJobCreateQueryResourceObject {
	return v.value
}

func (v *NullableProfileImportJobCreateQueryResourceObject) Set(val *ProfileImportJobCreateQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileImportJobCreateQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileImportJobCreateQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileImportJobCreateQueryResourceObject(val *ProfileImportJobCreateQueryResourceObject) *NullableProfileImportJobCreateQueryResourceObject {
	return &NullableProfileImportJobCreateQueryResourceObject{value: val, isSet: true}
}

func (v NullableProfileImportJobCreateQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileImportJobCreateQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


