/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImportErrorResponseObjectResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportErrorResponseObjectResource{}

// ImportErrorResponseObjectResource struct for ImportErrorResponseObjectResource
type ImportErrorResponseObjectResource struct {
	Type ImportErrorEnum `json:"type"`
	// Unique identifier for the error.
	Id string `json:"id"`
	Attributes ImportErrorResponseObjectResourceAttributes `json:"attributes"`
	Links ObjectLinks `json:"links"`
}

type _ImportErrorResponseObjectResource ImportErrorResponseObjectResource

// NewImportErrorResponseObjectResource instantiates a new ImportErrorResponseObjectResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportErrorResponseObjectResource(type_ ImportErrorEnum, id string, attributes ImportErrorResponseObjectResourceAttributes, links ObjectLinks) *ImportErrorResponseObjectResource {
	this := ImportErrorResponseObjectResource{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewImportErrorResponseObjectResourceWithDefaults instantiates a new ImportErrorResponseObjectResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportErrorResponseObjectResourceWithDefaults() *ImportErrorResponseObjectResource {
	this := ImportErrorResponseObjectResource{}
	return &this
}

// GetType returns the Type field value
func (o *ImportErrorResponseObjectResource) GetType() ImportErrorEnum {
	if o == nil {
		var ret ImportErrorEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ImportErrorResponseObjectResource) GetTypeOk() (*ImportErrorEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ImportErrorResponseObjectResource) SetType(v ImportErrorEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *ImportErrorResponseObjectResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ImportErrorResponseObjectResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ImportErrorResponseObjectResource) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *ImportErrorResponseObjectResource) GetAttributes() ImportErrorResponseObjectResourceAttributes {
	if o == nil {
		var ret ImportErrorResponseObjectResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ImportErrorResponseObjectResource) GetAttributesOk() (*ImportErrorResponseObjectResourceAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ImportErrorResponseObjectResource) SetAttributes(v ImportErrorResponseObjectResourceAttributes) {
	o.Attributes = v
}

// GetLinks returns the Links field value
func (o *ImportErrorResponseObjectResource) GetLinks() ObjectLinks {
	if o == nil {
		var ret ObjectLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ImportErrorResponseObjectResource) GetLinksOk() (*ObjectLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ImportErrorResponseObjectResource) SetLinks(v ObjectLinks) {
	o.Links = v
}

func (o ImportErrorResponseObjectResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportErrorResponseObjectResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ImportErrorResponseObjectResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportErrorResponseObjectResource := _ImportErrorResponseObjectResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImportErrorResponseObjectResource)

	if err != nil {
		return err
	}

	*o = ImportErrorResponseObjectResource(varImportErrorResponseObjectResource)

	return err
}

type NullableImportErrorResponseObjectResource struct {
	value *ImportErrorResponseObjectResource
	isSet bool
}

func (v NullableImportErrorResponseObjectResource) Get() *ImportErrorResponseObjectResource {
	return v.value
}

func (v *NullableImportErrorResponseObjectResource) Set(val *ImportErrorResponseObjectResource) {
	v.value = val
	v.isSet = true
}

func (v NullableImportErrorResponseObjectResource) IsSet() bool {
	return v.isSet
}

func (v *NullableImportErrorResponseObjectResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportErrorResponseObjectResource(val *ImportErrorResponseObjectResource) *NullableImportErrorResponseObjectResource {
	return &NullableImportErrorResponseObjectResource{value: val, isSet: true}
}

func (v NullableImportErrorResponseObjectResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportErrorResponseObjectResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


