/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the PostListCreateResponseDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostListCreateResponseDataRelationships{}

// PostListCreateResponseDataRelationships struct for PostListCreateResponseDataRelationships
type PostListCreateResponseDataRelationships struct {
	Profiles *PostListCreateResponseDataRelationshipsProfiles `json:"profiles,omitempty"`
	Tags *GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags `json:"tags,omitempty"`
}

// NewPostListCreateResponseDataRelationships instantiates a new PostListCreateResponseDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostListCreateResponseDataRelationships() *PostListCreateResponseDataRelationships {
	this := PostListCreateResponseDataRelationships{}
	return &this
}

// NewPostListCreateResponseDataRelationshipsWithDefaults instantiates a new PostListCreateResponseDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostListCreateResponseDataRelationshipsWithDefaults() *PostListCreateResponseDataRelationships {
	this := PostListCreateResponseDataRelationships{}
	return &this
}

// GetProfiles returns the Profiles field value if set, zero value otherwise.
func (o *PostListCreateResponseDataRelationships) GetProfiles() PostListCreateResponseDataRelationshipsProfiles {
	if o == nil || IsNil(o.Profiles) {
		var ret PostListCreateResponseDataRelationshipsProfiles
		return ret
	}
	return *o.Profiles
}

// GetProfilesOk returns a tuple with the Profiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostListCreateResponseDataRelationships) GetProfilesOk() (*PostListCreateResponseDataRelationshipsProfiles, bool) {
	if o == nil || IsNil(o.Profiles) {
		return nil, false
	}
	return o.Profiles, true
}

// HasProfiles returns a boolean if a field has been set.
func (o *PostListCreateResponseDataRelationships) HasProfiles() bool {
	if o != nil && !IsNil(o.Profiles) {
		return true
	}

	return false
}

// SetProfiles gets a reference to the given PostListCreateResponseDataRelationshipsProfiles and assigns it to the Profiles field.
func (o *PostListCreateResponseDataRelationships) SetProfiles(v PostListCreateResponseDataRelationshipsProfiles) {
	o.Profiles = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PostListCreateResponseDataRelationships) GetTags() GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags {
	if o == nil || IsNil(o.Tags) {
		var ret GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostListCreateResponseDataRelationships) GetTagsOk() (*GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PostListCreateResponseDataRelationships) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags and assigns it to the Tags field.
func (o *PostListCreateResponseDataRelationships) SetTags(v GetListListResponseCollectionCompoundDocumentDataInnerAllOfRelationshipsTags) {
	o.Tags = &v
}

func (o PostListCreateResponseDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostListCreateResponseDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profiles) {
		toSerialize["profiles"] = o.Profiles
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullablePostListCreateResponseDataRelationships struct {
	value *PostListCreateResponseDataRelationships
	isSet bool
}

func (v NullablePostListCreateResponseDataRelationships) Get() *PostListCreateResponseDataRelationships {
	return v.value
}

func (v *NullablePostListCreateResponseDataRelationships) Set(val *PostListCreateResponseDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullablePostListCreateResponseDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullablePostListCreateResponseDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostListCreateResponseDataRelationships(val *PostListCreateResponseDataRelationships) *NullablePostListCreateResponseDataRelationships {
	return &NullablePostListCreateResponseDataRelationships{value: val, isSet: true}
}

func (v NullablePostListCreateResponseDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostListCreateResponseDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


