/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCreateQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCreateQuery{}

// ListCreateQuery struct for ListCreateQuery
type ListCreateQuery struct {
	Data ListCreateQueryResourceObject `json:"data"`
}

type _ListCreateQuery ListCreateQuery

// NewListCreateQuery instantiates a new ListCreateQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCreateQuery(data ListCreateQueryResourceObject) *ListCreateQuery {
	this := ListCreateQuery{}
	this.Data = data
	return &this
}

// NewListCreateQueryWithDefaults instantiates a new ListCreateQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCreateQueryWithDefaults() *ListCreateQuery {
	this := ListCreateQuery{}
	return &this
}

// GetData returns the Data field value
func (o *ListCreateQuery) GetData() ListCreateQueryResourceObject {
	if o == nil {
		var ret ListCreateQueryResourceObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListCreateQuery) GetDataOk() (*ListCreateQueryResourceObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListCreateQuery) SetData(v ListCreateQueryResourceObject) {
	o.Data = v
}

func (o ListCreateQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCreateQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListCreateQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCreateQuery := _ListCreateQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCreateQuery)

	if err != nil {
		return err
	}

	*o = ListCreateQuery(varListCreateQuery)

	return err
}

type NullableListCreateQuery struct {
	value *ListCreateQuery
	isSet bool
}

func (v NullableListCreateQuery) Get() *ListCreateQuery {
	return v.value
}

func (v *NullableListCreateQuery) Set(val *ListCreateQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableListCreateQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableListCreateQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCreateQuery(val *ListCreateQuery) *NullableListCreateQuery {
	return &NullableListCreateQuery{value: val, isSet: true}
}

func (v NullableListCreateQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCreateQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


