/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the SMSChannel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SMSChannel{}

// SMSChannel struct for SMSChannel
type SMSChannel struct {
	Marketing *SMSMarketing `json:"marketing,omitempty"`
}

// NewSMSChannel instantiates a new SMSChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSMSChannel() *SMSChannel {
	this := SMSChannel{}
	return &this
}

// NewSMSChannelWithDefaults instantiates a new SMSChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSMSChannelWithDefaults() *SMSChannel {
	this := SMSChannel{}
	return &this
}

// GetMarketing returns the Marketing field value if set, zero value otherwise.
func (o *SMSChannel) GetMarketing() SMSMarketing {
	if o == nil || IsNil(o.Marketing) {
		var ret SMSMarketing
		return ret
	}
	return *o.Marketing
}

// GetMarketingOk returns a tuple with the Marketing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMSChannel) GetMarketingOk() (*SMSMarketing, bool) {
	if o == nil || IsNil(o.Marketing) {
		return nil, false
	}
	return o.Marketing, true
}

// HasMarketing returns a boolean if a field has been set.
func (o *SMSChannel) HasMarketing() bool {
	if o != nil && !IsNil(o.Marketing) {
		return true
	}

	return false
}

// SetMarketing gets a reference to the given SMSMarketing and assigns it to the Marketing field.
func (o *SMSChannel) SetMarketing(v SMSMarketing) {
	o.Marketing = &v
}

func (o SMSChannel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SMSChannel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Marketing) {
		toSerialize["marketing"] = o.Marketing
	}
	return toSerialize, nil
}

type NullableSMSChannel struct {
	value *SMSChannel
	isSet bool
}

func (v NullableSMSChannel) Get() *SMSChannel {
	return v.value
}

func (v *NullableSMSChannel) Set(val *SMSChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableSMSChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableSMSChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSMSChannel(val *SMSChannel) *NullableSMSChannel {
	return &NullableSMSChannel{value: val, isSet: true}
}

func (v NullableSMSChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSMSChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


