/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTagGroupResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTagGroupResponseData{}

// PostTagGroupResponseData struct for PostTagGroupResponseData
type PostTagGroupResponseData struct {
	Type TagGroupEnum `json:"type"`
	// The Tag Group ID
	Id string `json:"id"`
	Attributes TagGroupResponseObjectResourceAttributes `json:"attributes"`
	Relationships *PostTagGroupResponseDataRelationships `json:"relationships,omitempty"`
	Links ObjectLinks `json:"links"`
}

type _PostTagGroupResponseData PostTagGroupResponseData

// NewPostTagGroupResponseData instantiates a new PostTagGroupResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTagGroupResponseData(type_ TagGroupEnum, id string, attributes TagGroupResponseObjectResourceAttributes, links ObjectLinks) *PostTagGroupResponseData {
	this := PostTagGroupResponseData{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewPostTagGroupResponseDataWithDefaults instantiates a new PostTagGroupResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTagGroupResponseDataWithDefaults() *PostTagGroupResponseData {
	this := PostTagGroupResponseData{}
	return &this
}

// GetType returns the Type field value
func (o *PostTagGroupResponseData) GetType() TagGroupEnum {
	if o == nil {
		var ret TagGroupEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PostTagGroupResponseData) GetTypeOk() (*TagGroupEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PostTagGroupResponseData) SetType(v TagGroupEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *PostTagGroupResponseData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PostTagGroupResponseData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PostTagGroupResponseData) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *PostTagGroupResponseData) GetAttributes() TagGroupResponseObjectResourceAttributes {
	if o == nil {
		var ret TagGroupResponseObjectResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *PostTagGroupResponseData) GetAttributesOk() (*TagGroupResponseObjectResourceAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *PostTagGroupResponseData) SetAttributes(v TagGroupResponseObjectResourceAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *PostTagGroupResponseData) GetRelationships() PostTagGroupResponseDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret PostTagGroupResponseDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTagGroupResponseData) GetRelationshipsOk() (*PostTagGroupResponseDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *PostTagGroupResponseData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given PostTagGroupResponseDataRelationships and assigns it to the Relationships field.
func (o *PostTagGroupResponseData) SetRelationships(v PostTagGroupResponseDataRelationships) {
	o.Relationships = &v
}

// GetLinks returns the Links field value
func (o *PostTagGroupResponseData) GetLinks() ObjectLinks {
	if o == nil {
		var ret ObjectLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PostTagGroupResponseData) GetLinksOk() (*ObjectLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *PostTagGroupResponseData) SetLinks(v ObjectLinks) {
	o.Links = v
}

func (o PostTagGroupResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTagGroupResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *PostTagGroupResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTagGroupResponseData := _PostTagGroupResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTagGroupResponseData)

	if err != nil {
		return err
	}

	*o = PostTagGroupResponseData(varPostTagGroupResponseData)

	return err
}

type NullablePostTagGroupResponseData struct {
	value *PostTagGroupResponseData
	isSet bool
}

func (v NullablePostTagGroupResponseData) Get() *PostTagGroupResponseData {
	return v.value
}

func (v *NullablePostTagGroupResponseData) Set(val *PostTagGroupResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTagGroupResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTagGroupResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTagGroupResponseData(val *PostTagGroupResponseData) *NullablePostTagGroupResponseData {
	return &NullablePostTagGroupResponseData{value: val, isSet: true}
}

func (v NullablePostTagGroupResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTagGroupResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


