/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OnsiteSubscriptionCreateQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OnsiteSubscriptionCreateQueryResourceObject{}

// OnsiteSubscriptionCreateQueryResourceObject struct for OnsiteSubscriptionCreateQueryResourceObject
type OnsiteSubscriptionCreateQueryResourceObject struct {
	Type SubscriptionEnum `json:"type"`
	Attributes OnsiteSubscriptionCreateQueryResourceObjectAttributes `json:"attributes"`
	Relationships OnsiteSubscriptionCreateQueryResourceObjectRelationships `json:"relationships"`
}

type _OnsiteSubscriptionCreateQueryResourceObject OnsiteSubscriptionCreateQueryResourceObject

// NewOnsiteSubscriptionCreateQueryResourceObject instantiates a new OnsiteSubscriptionCreateQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOnsiteSubscriptionCreateQueryResourceObject(type_ SubscriptionEnum, attributes OnsiteSubscriptionCreateQueryResourceObjectAttributes, relationships OnsiteSubscriptionCreateQueryResourceObjectRelationships) *OnsiteSubscriptionCreateQueryResourceObject {
	this := OnsiteSubscriptionCreateQueryResourceObject{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewOnsiteSubscriptionCreateQueryResourceObjectWithDefaults instantiates a new OnsiteSubscriptionCreateQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOnsiteSubscriptionCreateQueryResourceObjectWithDefaults() *OnsiteSubscriptionCreateQueryResourceObject {
	this := OnsiteSubscriptionCreateQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetType() SubscriptionEnum {
	if o == nil {
		var ret SubscriptionEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetTypeOk() (*SubscriptionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) SetType(v SubscriptionEnum) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetAttributes() OnsiteSubscriptionCreateQueryResourceObjectAttributes {
	if o == nil {
		var ret OnsiteSubscriptionCreateQueryResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetAttributesOk() (*OnsiteSubscriptionCreateQueryResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) SetAttributes(v OnsiteSubscriptionCreateQueryResourceObjectAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetRelationships() OnsiteSubscriptionCreateQueryResourceObjectRelationships {
	if o == nil {
		var ret OnsiteSubscriptionCreateQueryResourceObjectRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *OnsiteSubscriptionCreateQueryResourceObject) GetRelationshipsOk() (*OnsiteSubscriptionCreateQueryResourceObjectRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *OnsiteSubscriptionCreateQueryResourceObject) SetRelationships(v OnsiteSubscriptionCreateQueryResourceObjectRelationships) {
	o.Relationships = v
}

func (o OnsiteSubscriptionCreateQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OnsiteSubscriptionCreateQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *OnsiteSubscriptionCreateQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOnsiteSubscriptionCreateQueryResourceObject := _OnsiteSubscriptionCreateQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOnsiteSubscriptionCreateQueryResourceObject)

	if err != nil {
		return err
	}

	*o = OnsiteSubscriptionCreateQueryResourceObject(varOnsiteSubscriptionCreateQueryResourceObject)

	return err
}

type NullableOnsiteSubscriptionCreateQueryResourceObject struct {
	value *OnsiteSubscriptionCreateQueryResourceObject
	isSet bool
}

func (v NullableOnsiteSubscriptionCreateQueryResourceObject) Get() *OnsiteSubscriptionCreateQueryResourceObject {
	return v.value
}

func (v *NullableOnsiteSubscriptionCreateQueryResourceObject) Set(val *OnsiteSubscriptionCreateQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableOnsiteSubscriptionCreateQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableOnsiteSubscriptionCreateQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOnsiteSubscriptionCreateQueryResourceObject(val *OnsiteSubscriptionCreateQueryResourceObject) *NullableOnsiteSubscriptionCreateQueryResourceObject {
	return &NullableOnsiteSubscriptionCreateQueryResourceObject{value: val, isSet: true}
}

func (v NullableOnsiteSubscriptionCreateQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOnsiteSubscriptionCreateQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


