/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
)

// checks if the ProfileMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfileMeta{}

// ProfileMeta struct for ProfileMeta
type ProfileMeta struct {
	PatchProperties *ProfileMetaPatchProperties `json:"patch_properties,omitempty"`
}

// NewProfileMeta instantiates a new ProfileMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfileMeta() *ProfileMeta {
	this := ProfileMeta{}
	return &this
}

// NewProfileMetaWithDefaults instantiates a new ProfileMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfileMetaWithDefaults() *ProfileMeta {
	this := ProfileMeta{}
	return &this
}

// GetPatchProperties returns the PatchProperties field value if set, zero value otherwise.
func (o *ProfileMeta) GetPatchProperties() ProfileMetaPatchProperties {
	if o == nil || IsNil(o.PatchProperties) {
		var ret ProfileMetaPatchProperties
		return ret
	}
	return *o.PatchProperties
}

// GetPatchPropertiesOk returns a tuple with the PatchProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfileMeta) GetPatchPropertiesOk() (*ProfileMetaPatchProperties, bool) {
	if o == nil || IsNil(o.PatchProperties) {
		return nil, false
	}
	return o.PatchProperties, true
}

// HasPatchProperties returns a boolean if a field has been set.
func (o *ProfileMeta) HasPatchProperties() bool {
	if o != nil && !IsNil(o.PatchProperties) {
		return true
	}

	return false
}

// SetPatchProperties gets a reference to the given ProfileMetaPatchProperties and assigns it to the PatchProperties field.
func (o *ProfileMeta) SetPatchProperties(v ProfileMetaPatchProperties) {
	o.PatchProperties = &v
}

func (o ProfileMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfileMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PatchProperties) {
		toSerialize["patch_properties"] = o.PatchProperties
	}
	return toSerialize, nil
}

type NullableProfileMeta struct {
	value *ProfileMeta
	isSet bool
}

func (v NullableProfileMeta) Get() *ProfileMeta {
	return v.value
}

func (v *NullableProfileMeta) Set(val *ProfileMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableProfileMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableProfileMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfileMeta(val *ProfileMeta) *NullableProfileMeta {
	return &NullableProfileMeta{value: val, isSet: true}
}

func (v NullableProfileMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfileMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


