/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCatalogCategoryDeleteJobResponseCollectionDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogCategoryDeleteJobResponseCollectionDataInner{}

// GetCatalogCategoryDeleteJobResponseCollectionDataInner struct for GetCatalogCategoryDeleteJobResponseCollectionDataInner
type GetCatalogCategoryDeleteJobResponseCollectionDataInner struct {
	Type CatalogCategoryBulkDeleteJobEnum `json:"type"`
	// Unique identifier for retrieving the job. Generated by Klaviyo.
	Id string `json:"id"`
	Attributes CouponCodeCreateJobResponseObjectResourceAttributes `json:"attributes"`
	Links ObjectLinks `json:"links"`
	Relationships *GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships `json:"relationships,omitempty"`
}

type _GetCatalogCategoryDeleteJobResponseCollectionDataInner GetCatalogCategoryDeleteJobResponseCollectionDataInner

// NewGetCatalogCategoryDeleteJobResponseCollectionDataInner instantiates a new GetCatalogCategoryDeleteJobResponseCollectionDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogCategoryDeleteJobResponseCollectionDataInner(type_ CatalogCategoryBulkDeleteJobEnum, id string, attributes CouponCodeCreateJobResponseObjectResourceAttributes, links ObjectLinks) *GetCatalogCategoryDeleteJobResponseCollectionDataInner {
	this := GetCatalogCategoryDeleteJobResponseCollectionDataInner{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerWithDefaults instantiates a new GetCatalogCategoryDeleteJobResponseCollectionDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogCategoryDeleteJobResponseCollectionDataInnerWithDefaults() *GetCatalogCategoryDeleteJobResponseCollectionDataInner {
	this := GetCatalogCategoryDeleteJobResponseCollectionDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetType() CatalogCategoryBulkDeleteJobEnum {
	if o == nil {
		var ret CatalogCategoryBulkDeleteJobEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetTypeOk() (*CatalogCategoryBulkDeleteJobEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) SetType(v CatalogCategoryBulkDeleteJobEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetAttributes() CouponCodeCreateJobResponseObjectResourceAttributes {
	if o == nil {
		var ret CouponCodeCreateJobResponseObjectResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetAttributesOk() (*CouponCodeCreateJobResponseObjectResourceAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) SetAttributes(v CouponCodeCreateJobResponseObjectResourceAttributes) {
	o.Attributes = v
}

// GetLinks returns the Links field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetLinks() ObjectLinks {
	if o == nil {
		var ret ObjectLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetLinksOk() (*ObjectLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) SetLinks(v ObjectLinks) {
	o.Links = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetRelationships() GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) GetRelationshipsOk() (*GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships and assigns it to the Relationships field.
func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) SetRelationships(v GetCatalogCategoryDeleteJobResponseCollectionDataInnerAllOfRelationships) {
	o.Relationships = &v
}

func (o GetCatalogCategoryDeleteJobResponseCollectionDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogCategoryDeleteJobResponseCollectionDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	toSerialize["links"] = o.Links
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *GetCatalogCategoryDeleteJobResponseCollectionDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCatalogCategoryDeleteJobResponseCollectionDataInner := _GetCatalogCategoryDeleteJobResponseCollectionDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCatalogCategoryDeleteJobResponseCollectionDataInner)

	if err != nil {
		return err
	}

	*o = GetCatalogCategoryDeleteJobResponseCollectionDataInner(varGetCatalogCategoryDeleteJobResponseCollectionDataInner)

	return err
}

type NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner struct {
	value *GetCatalogCategoryDeleteJobResponseCollectionDataInner
	isSet bool
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) Get() *GetCatalogCategoryDeleteJobResponseCollectionDataInner {
	return v.value
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) Set(val *GetCatalogCategoryDeleteJobResponseCollectionDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogCategoryDeleteJobResponseCollectionDataInner(val *GetCatalogCategoryDeleteJobResponseCollectionDataInner) *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner {
	return &NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner{value: val, isSet: true}
}

func (v NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogCategoryDeleteJobResponseCollectionDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


