/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"fmt"
)

// GetProfileResponseCompoundDocumentIncludedInner - struct for GetProfileResponseCompoundDocumentIncludedInner
type GetProfileResponseCompoundDocumentIncludedInner struct {
	ListResponseObjectResource *ListResponseObjectResource
	SegmentResponseObjectResource *SegmentResponseObjectResource
}

// ListResponseObjectResourceAsGetProfileResponseCompoundDocumentIncludedInner is a convenience function that returns ListResponseObjectResource wrapped in GetProfileResponseCompoundDocumentIncludedInner
func ListResponseObjectResourceAsGetProfileResponseCompoundDocumentIncludedInner(v *ListResponseObjectResource) GetProfileResponseCompoundDocumentIncludedInner {
	return GetProfileResponseCompoundDocumentIncludedInner{
		ListResponseObjectResource: v,
	}
}

// SegmentResponseObjectResourceAsGetProfileResponseCompoundDocumentIncludedInner is a convenience function that returns SegmentResponseObjectResource wrapped in GetProfileResponseCompoundDocumentIncludedInner
func SegmentResponseObjectResourceAsGetProfileResponseCompoundDocumentIncludedInner(v *SegmentResponseObjectResource) GetProfileResponseCompoundDocumentIncludedInner {
	return GetProfileResponseCompoundDocumentIncludedInner{
		SegmentResponseObjectResource: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetProfileResponseCompoundDocumentIncludedInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ListResponseObjectResource
	err = newStrictDecoder(data).Decode(&dst.ListResponseObjectResource)
	if err == nil {
		jsonListResponseObjectResource, _ := json.Marshal(dst.ListResponseObjectResource)
		if string(jsonListResponseObjectResource) == "{}" { // empty struct
			dst.ListResponseObjectResource = nil
		} else {
			match++
		}
	} else {
		dst.ListResponseObjectResource = nil
	}

	// try to unmarshal data into SegmentResponseObjectResource
	err = newStrictDecoder(data).Decode(&dst.SegmentResponseObjectResource)
	if err == nil {
		jsonSegmentResponseObjectResource, _ := json.Marshal(dst.SegmentResponseObjectResource)
		if string(jsonSegmentResponseObjectResource) == "{}" { // empty struct
			dst.SegmentResponseObjectResource = nil
		} else {
			match++
		}
	} else {
		dst.SegmentResponseObjectResource = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ListResponseObjectResource = nil
		dst.SegmentResponseObjectResource = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetProfileResponseCompoundDocumentIncludedInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetProfileResponseCompoundDocumentIncludedInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetProfileResponseCompoundDocumentIncludedInner) MarshalJSON() ([]byte, error) {
	if src.ListResponseObjectResource != nil {
		return json.Marshal(&src.ListResponseObjectResource)
	}

	if src.SegmentResponseObjectResource != nil {
		return json.Marshal(&src.SegmentResponseObjectResource)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetProfileResponseCompoundDocumentIncludedInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ListResponseObjectResource != nil {
		return obj.ListResponseObjectResource
	}

	if obj.SegmentResponseObjectResource != nil {
		return obj.SegmentResponseObjectResource
	}

	// all schemas are nil
	return nil
}

type NullableGetProfileResponseCompoundDocumentIncludedInner struct {
	value *GetProfileResponseCompoundDocumentIncludedInner
	isSet bool
}

func (v NullableGetProfileResponseCompoundDocumentIncludedInner) Get() *GetProfileResponseCompoundDocumentIncludedInner {
	return v.value
}

func (v *NullableGetProfileResponseCompoundDocumentIncludedInner) Set(val *GetProfileResponseCompoundDocumentIncludedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProfileResponseCompoundDocumentIncludedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProfileResponseCompoundDocumentIncludedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProfileResponseCompoundDocumentIncludedInner(val *GetProfileResponseCompoundDocumentIncludedInner) *NullableGetProfileResponseCompoundDocumentIncludedInner {
	return &NullableGetProfileResponseCompoundDocumentIncludedInner{value: val, isSet: true}
}

func (v NullableGetProfileResponseCompoundDocumentIncludedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProfileResponseCompoundDocumentIncludedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


