/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCatalogItemResponseCollectionCompoundDocumentDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCatalogItemResponseCollectionCompoundDocumentDataInner{}

// GetCatalogItemResponseCollectionCompoundDocumentDataInner struct for GetCatalogItemResponseCollectionCompoundDocumentDataInner
type GetCatalogItemResponseCollectionCompoundDocumentDataInner struct {
	Type CatalogItemEnum `json:"type"`
	// The catalog item ID is a compound ID (string), with format: `{integration}:::{catalog}:::{external_id}`. Currently, the only supported integration type is `$custom`, and the only supported catalog is `$default`.
	Id string `json:"id"`
	Attributes CatalogItemResponseObjectResourceAttributes `json:"attributes"`
	Links ObjectLinks `json:"links"`
	Relationships *GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships `json:"relationships,omitempty"`
}

type _GetCatalogItemResponseCollectionCompoundDocumentDataInner GetCatalogItemResponseCollectionCompoundDocumentDataInner

// NewGetCatalogItemResponseCollectionCompoundDocumentDataInner instantiates a new GetCatalogItemResponseCollectionCompoundDocumentDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogItemResponseCollectionCompoundDocumentDataInner(type_ CatalogItemEnum, id string, attributes CatalogItemResponseObjectResourceAttributes, links ObjectLinks) *GetCatalogItemResponseCollectionCompoundDocumentDataInner {
	this := GetCatalogItemResponseCollectionCompoundDocumentDataInner{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	this.Links = links
	return &this
}

// NewGetCatalogItemResponseCollectionCompoundDocumentDataInnerWithDefaults instantiates a new GetCatalogItemResponseCollectionCompoundDocumentDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogItemResponseCollectionCompoundDocumentDataInnerWithDefaults() *GetCatalogItemResponseCollectionCompoundDocumentDataInner {
	this := GetCatalogItemResponseCollectionCompoundDocumentDataInner{}
	return &this
}

// GetType returns the Type field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetType() CatalogItemEnum {
	if o == nil {
		var ret CatalogItemEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetTypeOk() (*CatalogItemEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) SetType(v CatalogItemEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetAttributes() CatalogItemResponseObjectResourceAttributes {
	if o == nil {
		var ret CatalogItemResponseObjectResourceAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetAttributesOk() (*CatalogItemResponseObjectResourceAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) SetAttributes(v CatalogItemResponseObjectResourceAttributes) {
	o.Attributes = v
}

// GetLinks returns the Links field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetLinks() ObjectLinks {
	if o == nil {
		var ret ObjectLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetLinksOk() (*ObjectLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) SetLinks(v ObjectLinks) {
	o.Links = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetRelationships() GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) GetRelationshipsOk() (*GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships and assigns it to the Relationships field.
func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) SetRelationships(v GetCatalogItemResponseCollectionCompoundDocumentDataInnerAllOfRelationships) {
	o.Relationships = &v
}

func (o GetCatalogItemResponseCollectionCompoundDocumentDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCatalogItemResponseCollectionCompoundDocumentDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	toSerialize["links"] = o.Links
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *GetCatalogItemResponseCollectionCompoundDocumentDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCatalogItemResponseCollectionCompoundDocumentDataInner := _GetCatalogItemResponseCollectionCompoundDocumentDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCatalogItemResponseCollectionCompoundDocumentDataInner)

	if err != nil {
		return err
	}

	*o = GetCatalogItemResponseCollectionCompoundDocumentDataInner(varGetCatalogItemResponseCollectionCompoundDocumentDataInner)

	return err
}

type NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner struct {
	value *GetCatalogItemResponseCollectionCompoundDocumentDataInner
	isSet bool
}

func (v NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) Get() *GetCatalogItemResponseCollectionCompoundDocumentDataInner {
	return v.value
}

func (v *NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) Set(val *GetCatalogItemResponseCollectionCompoundDocumentDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogItemResponseCollectionCompoundDocumentDataInner(val *GetCatalogItemResponseCollectionCompoundDocumentDataInner) *NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner {
	return &NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner{value: val, isSet: true}
}

func (v NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogItemResponseCollectionCompoundDocumentDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


