/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles{}

// SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles The profile(s) to unsubscribe
type SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles struct {
	Data []ProfileSubscriptionDeleteQueryResourceObject `json:"data"`
}

type _SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles

// NewSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles instantiates a new SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles(data []ProfileSubscriptionDeleteQueryResourceObject) *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles {
	this := SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles{}
	this.Data = data
	return &this
}

// NewSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfilesWithDefaults instantiates a new SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfilesWithDefaults() *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles {
	this := SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles{}
	return &this
}

// GetData returns the Data field value
func (o *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) GetData() []ProfileSubscriptionDeleteQueryResourceObject {
	if o == nil {
		var ret []ProfileSubscriptionDeleteQueryResourceObject
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) GetDataOk() ([]ProfileSubscriptionDeleteQueryResourceObject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) SetData(v []ProfileSubscriptionDeleteQueryResourceObject) {
	o.Data = v
}

func (o SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles := _SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles)

	if err != nil {
		return err
	}

	*o = SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles(varSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles)

	return err
}

type NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles struct {
	value *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles
	isSet bool
}

func (v NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) Get() *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles {
	return v.value
}

func (v *NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) Set(val *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles(val *SubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) *NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles {
	return &NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles{value: val, isSet: true}
}

func (v NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionDeleteJobCreateQueryResourceObjectAttributesProfiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


