/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostListCreateResponseDataRelationshipsProfiles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostListCreateResponseDataRelationshipsProfiles{}

// PostListCreateResponseDataRelationshipsProfiles struct for PostListCreateResponseDataRelationshipsProfiles
type PostListCreateResponseDataRelationshipsProfiles struct {
	Data []GetListRelationshipsResponseCollectionDataInner `json:"data"`
	Links *RelationshipLinks `json:"links,omitempty"`
}

type _PostListCreateResponseDataRelationshipsProfiles PostListCreateResponseDataRelationshipsProfiles

// NewPostListCreateResponseDataRelationshipsProfiles instantiates a new PostListCreateResponseDataRelationshipsProfiles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostListCreateResponseDataRelationshipsProfiles(data []GetListRelationshipsResponseCollectionDataInner) *PostListCreateResponseDataRelationshipsProfiles {
	this := PostListCreateResponseDataRelationshipsProfiles{}
	this.Data = data
	return &this
}

// NewPostListCreateResponseDataRelationshipsProfilesWithDefaults instantiates a new PostListCreateResponseDataRelationshipsProfiles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostListCreateResponseDataRelationshipsProfilesWithDefaults() *PostListCreateResponseDataRelationshipsProfiles {
	this := PostListCreateResponseDataRelationshipsProfiles{}
	return &this
}

// GetData returns the Data field value
func (o *PostListCreateResponseDataRelationshipsProfiles) GetData() []GetListRelationshipsResponseCollectionDataInner {
	if o == nil {
		var ret []GetListRelationshipsResponseCollectionDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PostListCreateResponseDataRelationshipsProfiles) GetDataOk() ([]GetListRelationshipsResponseCollectionDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PostListCreateResponseDataRelationshipsProfiles) SetData(v []GetListRelationshipsResponseCollectionDataInner) {
	o.Data = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *PostListCreateResponseDataRelationshipsProfiles) GetLinks() RelationshipLinks {
	if o == nil || IsNil(o.Links) {
		var ret RelationshipLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostListCreateResponseDataRelationshipsProfiles) GetLinksOk() (*RelationshipLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *PostListCreateResponseDataRelationshipsProfiles) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given RelationshipLinks and assigns it to the Links field.
func (o *PostListCreateResponseDataRelationshipsProfiles) SetLinks(v RelationshipLinks) {
	o.Links = &v
}

func (o PostListCreateResponseDataRelationshipsProfiles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostListCreateResponseDataRelationshipsProfiles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

func (o *PostListCreateResponseDataRelationshipsProfiles) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostListCreateResponseDataRelationshipsProfiles := _PostListCreateResponseDataRelationshipsProfiles{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostListCreateResponseDataRelationshipsProfiles)

	if err != nil {
		return err
	}

	*o = PostListCreateResponseDataRelationshipsProfiles(varPostListCreateResponseDataRelationshipsProfiles)

	return err
}

type NullablePostListCreateResponseDataRelationshipsProfiles struct {
	value *PostListCreateResponseDataRelationshipsProfiles
	isSet bool
}

func (v NullablePostListCreateResponseDataRelationshipsProfiles) Get() *PostListCreateResponseDataRelationshipsProfiles {
	return v.value
}

func (v *NullablePostListCreateResponseDataRelationshipsProfiles) Set(val *PostListCreateResponseDataRelationshipsProfiles) {
	v.value = val
	v.isSet = true
}

func (v NullablePostListCreateResponseDataRelationshipsProfiles) IsSet() bool {
	return v.isSet
}

func (v *NullablePostListCreateResponseDataRelationshipsProfiles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostListCreateResponseDataRelationshipsProfiles(val *PostListCreateResponseDataRelationshipsProfiles) *NullablePostListCreateResponseDataRelationshipsProfiles {
	return &NullablePostListCreateResponseDataRelationshipsProfiles{value: val, isSet: true}
}

func (v NullablePostListCreateResponseDataRelationshipsProfiles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostListCreateResponseDataRelationshipsProfiles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


