/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CampaignCloneQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignCloneQueryResourceObject{}

// CampaignCloneQueryResourceObject struct for CampaignCloneQueryResourceObject
type CampaignCloneQueryResourceObject struct {
	Type CampaignEnum `json:"type"`
	// The campaign ID to be cloned
	Id string `json:"id"`
	Attributes CampaignCloneQueryResourceObjectAttributes `json:"attributes"`
}

type _CampaignCloneQueryResourceObject CampaignCloneQueryResourceObject

// NewCampaignCloneQueryResourceObject instantiates a new CampaignCloneQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignCloneQueryResourceObject(type_ CampaignEnum, id string, attributes CampaignCloneQueryResourceObjectAttributes) *CampaignCloneQueryResourceObject {
	this := CampaignCloneQueryResourceObject{}
	this.Type = type_
	this.Id = id
	this.Attributes = attributes
	return &this
}

// NewCampaignCloneQueryResourceObjectWithDefaults instantiates a new CampaignCloneQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignCloneQueryResourceObjectWithDefaults() *CampaignCloneQueryResourceObject {
	this := CampaignCloneQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *CampaignCloneQueryResourceObject) GetType() CampaignEnum {
	if o == nil {
		var ret CampaignEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CampaignCloneQueryResourceObject) GetTypeOk() (*CampaignEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CampaignCloneQueryResourceObject) SetType(v CampaignEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CampaignCloneQueryResourceObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CampaignCloneQueryResourceObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CampaignCloneQueryResourceObject) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value
func (o *CampaignCloneQueryResourceObject) GetAttributes() CampaignCloneQueryResourceObjectAttributes {
	if o == nil {
		var ret CampaignCloneQueryResourceObjectAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CampaignCloneQueryResourceObject) GetAttributesOk() (*CampaignCloneQueryResourceObjectAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CampaignCloneQueryResourceObject) SetAttributes(v CampaignCloneQueryResourceObjectAttributes) {
	o.Attributes = v
}

func (o CampaignCloneQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignCloneQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CampaignCloneQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaignCloneQueryResourceObject := _CampaignCloneQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCampaignCloneQueryResourceObject)

	if err != nil {
		return err
	}

	*o = CampaignCloneQueryResourceObject(varCampaignCloneQueryResourceObject)

	return err
}

type NullableCampaignCloneQueryResourceObject struct {
	value *CampaignCloneQueryResourceObject
	isSet bool
}

func (v NullableCampaignCloneQueryResourceObject) Get() *CampaignCloneQueryResourceObject {
	return v.value
}

func (v *NullableCampaignCloneQueryResourceObject) Set(val *CampaignCloneQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignCloneQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignCloneQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignCloneQueryResourceObject(val *CampaignCloneQueryResourceObject) *NullableCampaignCloneQueryResourceObject {
	return &NullableCampaignCloneQueryResourceObject{value: val, isSet: true}
}

func (v NullableCampaignCloneQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignCloneQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


