/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatalogVariantDeleteQueryResourceObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogVariantDeleteQueryResourceObject{}

// CatalogVariantDeleteQueryResourceObject struct for CatalogVariantDeleteQueryResourceObject
type CatalogVariantDeleteQueryResourceObject struct {
	Type CatalogVariantEnum `json:"type"`
	// The catalog variant ID is a compound ID (string), with format: `{integration}:::{catalog}:::{external_id}`. Currently, the only supported integration type is `$custom`, and the only supported catalog is `$default`.
	Id string `json:"id"`
}

type _CatalogVariantDeleteQueryResourceObject CatalogVariantDeleteQueryResourceObject

// NewCatalogVariantDeleteQueryResourceObject instantiates a new CatalogVariantDeleteQueryResourceObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogVariantDeleteQueryResourceObject(type_ CatalogVariantEnum, id string) *CatalogVariantDeleteQueryResourceObject {
	this := CatalogVariantDeleteQueryResourceObject{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewCatalogVariantDeleteQueryResourceObjectWithDefaults instantiates a new CatalogVariantDeleteQueryResourceObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogVariantDeleteQueryResourceObjectWithDefaults() *CatalogVariantDeleteQueryResourceObject {
	this := CatalogVariantDeleteQueryResourceObject{}
	return &this
}

// GetType returns the Type field value
func (o *CatalogVariantDeleteQueryResourceObject) GetType() CatalogVariantEnum {
	if o == nil {
		var ret CatalogVariantEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CatalogVariantDeleteQueryResourceObject) GetTypeOk() (*CatalogVariantEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CatalogVariantDeleteQueryResourceObject) SetType(v CatalogVariantEnum) {
	o.Type = v
}

// GetId returns the Id field value
func (o *CatalogVariantDeleteQueryResourceObject) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CatalogVariantDeleteQueryResourceObject) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CatalogVariantDeleteQueryResourceObject) SetId(v string) {
	o.Id = v
}

func (o CatalogVariantDeleteQueryResourceObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogVariantDeleteQueryResourceObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CatalogVariantDeleteQueryResourceObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatalogVariantDeleteQueryResourceObject := _CatalogVariantDeleteQueryResourceObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatalogVariantDeleteQueryResourceObject)

	if err != nil {
		return err
	}

	*o = CatalogVariantDeleteQueryResourceObject(varCatalogVariantDeleteQueryResourceObject)

	return err
}

type NullableCatalogVariantDeleteQueryResourceObject struct {
	value *CatalogVariantDeleteQueryResourceObject
	isSet bool
}

func (v NullableCatalogVariantDeleteQueryResourceObject) Get() *CatalogVariantDeleteQueryResourceObject {
	return v.value
}

func (v *NullableCatalogVariantDeleteQueryResourceObject) Set(val *CatalogVariantDeleteQueryResourceObject) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogVariantDeleteQueryResourceObject) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogVariantDeleteQueryResourceObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogVariantDeleteQueryResourceObject(val *CatalogVariantDeleteQueryResourceObject) *NullableCatalogVariantDeleteQueryResourceObject {
	return &NullableCatalogVariantDeleteQueryResourceObject{value: val, isSet: true}
}

func (v NullableCatalogVariantDeleteQueryResourceObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogVariantDeleteQueryResourceObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


