/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetTagResponseCompoundDocument type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTagResponseCompoundDocument{}

// GetTagResponseCompoundDocument struct for GetTagResponseCompoundDocument
type GetTagResponseCompoundDocument struct {
	Data GetTagResponseCollectionCompoundDocumentDataInner `json:"data"`
	Included []TagGroupResponseObjectResource `json:"included,omitempty"`
}

type _GetTagResponseCompoundDocument GetTagResponseCompoundDocument

// NewGetTagResponseCompoundDocument instantiates a new GetTagResponseCompoundDocument object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTagResponseCompoundDocument(data GetTagResponseCollectionCompoundDocumentDataInner) *GetTagResponseCompoundDocument {
	this := GetTagResponseCompoundDocument{}
	this.Data = data
	return &this
}

// NewGetTagResponseCompoundDocumentWithDefaults instantiates a new GetTagResponseCompoundDocument object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTagResponseCompoundDocumentWithDefaults() *GetTagResponseCompoundDocument {
	this := GetTagResponseCompoundDocument{}
	return &this
}

// GetData returns the Data field value
func (o *GetTagResponseCompoundDocument) GetData() GetTagResponseCollectionCompoundDocumentDataInner {
	if o == nil {
		var ret GetTagResponseCollectionCompoundDocumentDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetTagResponseCompoundDocument) GetDataOk() (*GetTagResponseCollectionCompoundDocumentDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetTagResponseCompoundDocument) SetData(v GetTagResponseCollectionCompoundDocumentDataInner) {
	o.Data = v
}

// GetIncluded returns the Included field value if set, zero value otherwise.
func (o *GetTagResponseCompoundDocument) GetIncluded() []TagGroupResponseObjectResource {
	if o == nil || IsNil(o.Included) {
		var ret []TagGroupResponseObjectResource
		return ret
	}
	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTagResponseCompoundDocument) GetIncludedOk() ([]TagGroupResponseObjectResource, bool) {
	if o == nil || IsNil(o.Included) {
		return nil, false
	}
	return o.Included, true
}

// HasIncluded returns a boolean if a field has been set.
func (o *GetTagResponseCompoundDocument) HasIncluded() bool {
	if o != nil && !IsNil(o.Included) {
		return true
	}

	return false
}

// SetIncluded gets a reference to the given []TagGroupResponseObjectResource and assigns it to the Included field.
func (o *GetTagResponseCompoundDocument) SetIncluded(v []TagGroupResponseObjectResource) {
	o.Included = v
}

func (o GetTagResponseCompoundDocument) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTagResponseCompoundDocument) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.Included) {
		toSerialize["included"] = o.Included
	}
	return toSerialize, nil
}

func (o *GetTagResponseCompoundDocument) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTagResponseCompoundDocument := _GetTagResponseCompoundDocument{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTagResponseCompoundDocument)

	if err != nil {
		return err
	}

	*o = GetTagResponseCompoundDocument(varGetTagResponseCompoundDocument)

	return err
}

type NullableGetTagResponseCompoundDocument struct {
	value *GetTagResponseCompoundDocument
	isSet bool
}

func (v NullableGetTagResponseCompoundDocument) Get() *GetTagResponseCompoundDocument {
	return v.value
}

func (v *NullableGetTagResponseCompoundDocument) Set(val *GetTagResponseCompoundDocument) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTagResponseCompoundDocument) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTagResponseCompoundDocument) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTagResponseCompoundDocument(val *GetTagResponseCompoundDocument) *NullableGetTagResponseCompoundDocument {
	return &NullableGetTagResponseCompoundDocument{value: val, isSet: true}
}

func (v NullableGetTagResponseCompoundDocument) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTagResponseCompoundDocument) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


