/*
Klaviyo API

The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.

API version: 2024-02-15
Contact: developers@klaviyo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package klaviyo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetCampaignMessageTemplateRelationshipListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCampaignMessageTemplateRelationshipListResponse{}

// GetCampaignMessageTemplateRelationshipListResponse struct for GetCampaignMessageTemplateRelationshipListResponse
type GetCampaignMessageTemplateRelationshipListResponse struct {
	Data GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData `json:"data"`
}

type _GetCampaignMessageTemplateRelationshipListResponse GetCampaignMessageTemplateRelationshipListResponse

// NewGetCampaignMessageTemplateRelationshipListResponse instantiates a new GetCampaignMessageTemplateRelationshipListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCampaignMessageTemplateRelationshipListResponse(data GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData) *GetCampaignMessageTemplateRelationshipListResponse {
	this := GetCampaignMessageTemplateRelationshipListResponse{}
	this.Data = data
	return &this
}

// NewGetCampaignMessageTemplateRelationshipListResponseWithDefaults instantiates a new GetCampaignMessageTemplateRelationshipListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCampaignMessageTemplateRelationshipListResponseWithDefaults() *GetCampaignMessageTemplateRelationshipListResponse {
	this := GetCampaignMessageTemplateRelationshipListResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetCampaignMessageTemplateRelationshipListResponse) GetData() GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData {
	if o == nil {
		var ret GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetCampaignMessageTemplateRelationshipListResponse) GetDataOk() (*GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetCampaignMessageTemplateRelationshipListResponse) SetData(v GetFlowMessageResponseCompoundDocumentDataAllOfRelationshipsTemplateData) {
	o.Data = v
}

func (o GetCampaignMessageTemplateRelationshipListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCampaignMessageTemplateRelationshipListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetCampaignMessageTemplateRelationshipListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCampaignMessageTemplateRelationshipListResponse := _GetCampaignMessageTemplateRelationshipListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetCampaignMessageTemplateRelationshipListResponse)

	if err != nil {
		return err
	}

	*o = GetCampaignMessageTemplateRelationshipListResponse(varGetCampaignMessageTemplateRelationshipListResponse)

	return err
}

type NullableGetCampaignMessageTemplateRelationshipListResponse struct {
	value *GetCampaignMessageTemplateRelationshipListResponse
	isSet bool
}

func (v NullableGetCampaignMessageTemplateRelationshipListResponse) Get() *GetCampaignMessageTemplateRelationshipListResponse {
	return v.value
}

func (v *NullableGetCampaignMessageTemplateRelationshipListResponse) Set(val *GetCampaignMessageTemplateRelationshipListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCampaignMessageTemplateRelationshipListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCampaignMessageTemplateRelationshipListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCampaignMessageTemplateRelationshipListResponse(val *GetCampaignMessageTemplateRelationshipListResponse) *NullableGetCampaignMessageTemplateRelationshipListResponse {
	return &NullableGetCampaignMessageTemplateRelationshipListResponse{value: val, isSet: true}
}

func (v NullableGetCampaignMessageTemplateRelationshipListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCampaignMessageTemplateRelationshipListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


